- name: Create SSH config
  template:
    src: ssh_config
    dest: /home/cephuser/.ssh/config
    owner: cephuser
    group: cephuser
    mode: 0600

- name: Copy keys
  copy:
    src: files/{{ item }}
    dest: /home/cephuser/.ssh/{{ item }}
    owner: cephuser
    group: cephuser
    mode: 0600
  with_items:
    - id_rsa
    - id_rsa.pub

- name: known_hosts
  copy:
    src: files/known_hosts
    dest: /home/cephuser/.ssh/known_hosts
    owner: cephuser
    group: cephuser
    mode: 0600

- name: Install Ceph Repo
  yum:
    name: http://download.ceph.com/rpm-jewel/el7/noarch/ceph-release-1-1.el7.noarch.rpm
    state: present
    disable_gpg_check: true

- name: Install Cephadmin
  yum:
    name: ceph-deploy
    state: present